version: '3.1'

services:

  db:
    image: shaddar/postgres12:v1
    restart: always
    environment:
      POSTGRES_USER: shaddar
      POSTGRES_PASSWORD: shaddar91
      POSTGRES_DB: shad


  be:
    image: shaddar/flask:v1
    restart: always
    ports:
      - 8081:8080
    volumes:
      - be:/var/www/app